# Generated by Django 2.2.4 on 2019-08-21 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoPad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DjangoBoard',
            new_name='MemoAppModel',
        ),
    ]
