# Generated by Django 2.2.4 on 2019-08-23 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='memo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='memos.Memo'),
        ),
        migrations.AlterField(
            model_name='like',
            name='memo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='memos.Memo'),
        ),
    ]
