# Generated by Django 2.2.4 on 2019-09-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='username',
            new_name='password',
        ),
    ]
