# Generated by Django 2.2.4 on 2019-08-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='userId',
            field=models.CharField(default='anonymous', max_length=50),
        ),
    ]
